import { City } from '@/lib/types';

export const mockCities: City[] = [
  {
    id: 'city-1',
    name: '서울',
    slug: 'seoul',
    region: '수도권',
    description: '대한민국의 수도이자 최대 도시. 현대적인 인프라와 전통이 공존하는 곳.',
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017',
    rating: 4.5,
    reviewCount: 127,
    costOfLiving: 2500000,
    internetSpeed: 300,
    temperature: { summer: 28, winter: -2 },
    tags: ['대도시', '스타트업', '카페', '교통편리'],
    highlights: ['강남 코워킹스페이스', '홍대 카페 거리', '한강 공원'],
    recommendedPlaces: [
      { name: '패스트파이브 강남점', type: 'coworking', description: '강남역 근처 프리미엄 코워킹 스페이스' },
      { name: '카페 온즈', type: 'cafe', description: '성수동 감성 카페, 작업하기 좋은 분위기' },
      { name: '국립중앙도서관', type: 'library', description: '무료 열람실과 WiFi 제공' },
    ],
    transportation: {
      subway: true,
      bus: '우수',
      airport: '인천공항 1시간',
      walkability: 4,
    },
    climate: {
      spring: '쾌적함 (10-20°C)',
      summer: '덥고 습함 (25-30°C)',
      fall: '선선함 (10-20°C)',
      winter: '춥고 건조함 (-5-5°C)',
      rainySeasonStart: '6월 말',
      rainySeasonEnd: '7월 말',
    },
  },
  {
    id: 'city-2',
    name: '부산',
    slug: 'busan',
    region: '경상도',
    description: '대한민국 제2의 도시. 아름다운 해변과 활기찬 분위기.',
    image: 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22',
    rating: 4.7,
    reviewCount: 89,
    costOfLiving: 1800000,
    internetSpeed: 280,
    temperature: { summer: 26, winter: 3 },
    tags: ['해변', '항구', '온천', '저렴'],
    highlights: ['해운대 해수욕장', '광안리 카페', '영화의전당'],
    recommendedPlaces: [
      { name: '커먼그라운드 부산', type: 'coworking', description: '센텀시티 복합 코워킹 스페이스' },
      { name: '테라로사 커피', type: 'cafe', description: '광안리 오션뷰 카페' },
      { name: '해운대 바다 도서관', type: 'library', description: '바다가 보이는 공공 도서관' },
    ],
    transportation: {
      subway: true,
      bus: '우수',
      airport: '김해공항 30분',
      walkability: 3,
    },
    climate: {
      spring: '온화함 (12-18°C)',
      summer: '덥지만 서울보다 선선 (23-28°C)',
      fall: '따뜻함 (15-22°C)',
      winter: '온화함 (3-8°C)',
      rainySeasonStart: '6월 말',
      rainySeasonEnd: '7월 말',
    },
  },
  {
    id: 'city-3',
    name: '제주',
    slug: 'jeju',
    region: '제주특별자치도',
    description: '한국의 하와이. 자연 경관이 뛰어난 섬.',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19',
    rating: 4.8,
    reviewCount: 156,
    costOfLiving: 2200000,
    internetSpeed: 250,
    temperature: { summer: 27, winter: 7 },
    tags: ['섬', '자연', '힐링', '카페'],
    highlights: ['한라산', '성산일출봉', '월정리 카페거리'],
    recommendedPlaces: [
      { name: '더그레잇스페이스', type: 'coworking', description: '제주 제일 큰 코워킹 스페이스' },
      { name: '카페 델문도', type: 'cafe', description: '월정리 해변 뷰 카페' },
      { name: '제주시립 중앙도서관', type: 'library', description: '제주 시내 중심 도서관' },
    ],
    transportation: {
      subway: false,
      bus: '보통',
      airport: '제주공항 30분',
      walkability: 2,
    },
    climate: {
      spring: '온화하고 꽃이 많음 (12-18°C)',
      summer: '따뜻하고 습함 (25-30°C)',
      fall: '쾌적함 (15-22°C)',
      winter: '온화함 (5-10°C)',
      rainySeasonStart: '6월',
      rainySeasonEnd: '9월',
    },
  },
  {
    id: 'city-4',
    name: '인천',
    slug: 'incheon',
    region: '수도권',
    description: '서울과 인접한 항구 도시. 국제공항이 있어 접근성이 좋음.',
    image: 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22',
    rating: 4.3,
    reviewCount: 45,
    costOfLiving: 2000000,
    internetSpeed: 290,
    temperature: { summer: 27, winter: -1 },
    tags: ['공항', '항구', '차이나타운', '교통편리'],
    highlights: ['송도 센트럴파크', '인천공항', '월미도'],
  },
  {
    id: 'city-5',
    name: '대전',
    slug: 'daejeon',
    region: '충청도',
    description: '과학과 교육의 도시. 중부권의 중심지.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.4,
    reviewCount: 38,
    costOfLiving: 1600000,
    internetSpeed: 270,
    temperature: { summer: 27, winter: -1 },
    tags: ['과학', '교육', '저렴', '조용함'],
    highlights: ['대덕연구단지', '엑스포과학공원', '성심당'],
  },
  {
    id: 'city-6',
    name: '대구',
    slug: 'daegu',
    region: '경상도',
    description: '따뜻한 분위기의 도시. 패션과 문화의 중심지.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.2,
    reviewCount: 42,
    costOfLiving: 1700000,
    internetSpeed: 260,
    temperature: { summer: 29, winter: 1 },
    tags: ['패션', '문화', '따뜻함', '저렴'],
    highlights: ['동성로', '김광석거리', '앞산전망대'],
  },
  {
    id: 'city-7',
    name: '광주',
    slug: 'gwangju',
    region: '전라도',
    description: '예술과 미식의 도시. 문화가 살아 숨쉬는 곳.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.3,
    reviewCount: 35,
    costOfLiving: 1650000,
    internetSpeed: 265,
    temperature: { summer: 28, winter: 1 },
    tags: ['예술', '미식', '역사', '저렴'],
    highlights: ['양림동 카페거리', '무등산', '국립아시아문화전당'],
  },
  {
    id: 'city-8',
    name: '울산',
    slug: 'ulsan',
    region: '경상도',
    description: '산업 도시이자 해양 관광의 명소.',
    image: 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22',
    rating: 4.1,
    reviewCount: 28,
    costOfLiving: 1750000,
    internetSpeed: 270,
    temperature: { summer: 26, winter: 2 },
    tags: ['산업', '해변', '조용함', '안정적'],
    highlights: ['간절곶', '대왕암공원', '태화강'],
  },
  {
    id: 'city-9',
    name: '수원',
    slug: 'suwon',
    region: '수도권',
    description: '역사와 현대가 조화를 이루는 경기도의 중심.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.2,
    reviewCount: 31,
    costOfLiving: 1900000,
    internetSpeed: 285,
    temperature: { summer: 27, winter: -2 },
    tags: ['역사', '성곽', '교통편리', '삼성'],
    highlights: ['수원화성', '행궁동 카페거리', '광교호수공원'],
  },
  {
    id: 'city-10',
    name: '성남',
    slug: 'seongnam',
    region: '수도권',
    description: 'IT와 첨단산업의 중심지. 판교 테크노밸리가 있는 곳.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.4,
    reviewCount: 52,
    costOfLiving: 2100000,
    internetSpeed: 300,
    temperature: { summer: 27, winter: -2 },
    tags: ['IT', '스타트업', '현대적', '교통편리'],
    highlights: ['판교 테크노밸리', '백현동 카페거리', '탄천'],
  },
  {
    id: 'city-11',
    name: '전주',
    slug: 'jeonju',
    region: '전라도',
    description: '전통 한옥과 맛의 도시. 슬로우 라이프를 즐기기 좋은 곳.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.6,
    reviewCount: 67,
    costOfLiving: 1500000,
    internetSpeed: 240,
    temperature: { summer: 28, winter: 0 },
    tags: ['한옥', '미식', '전통', '힐링'],
    highlights: ['전주한옥마을', '객사길', '덕진공원'],
  },
  {
    id: 'city-12',
    name: '천안',
    slug: 'cheonan',
    region: '충청도',
    description: '교통의 요충지. 서울과 지방을 잇는 중간 거점.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.0,
    reviewCount: 22,
    costOfLiving: 1550000,
    internetSpeed: 260,
    temperature: { summer: 27, winter: -1 },
    tags: ['교통', '저렴', '조용함', '안정적'],
    highlights: ['독립기념관', '천안삼거리공원', '성환역'],
  },
  {
    id: 'city-13',
    name: '강릉',
    slug: 'gangneung',
    region: '강원도',
    description: '동해안의 아름다운 해변 도시. 커피의 도시.',
    image: 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22',
    rating: 4.7,
    reviewCount: 78,
    costOfLiving: 1700000,
    internetSpeed: 240,
    temperature: { summer: 25, winter: -1 },
    tags: ['해변', '커피', '자연', '힐링'],
    highlights: ['안목 커피거리', '경포대', '오죽헌'],
  },
  {
    id: 'city-14',
    name: '춘천',
    slug: 'chuncheon',
    region: '강원도',
    description: '호수의 도시. 자연 속에서 일하기 좋은 곳.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.5,
    reviewCount: 44,
    costOfLiving: 1600000,
    internetSpeed: 230,
    temperature: { summer: 26, winter: -4 },
    tags: ['호수', '자연', '조용함', '저렴'],
    highlights: ['소양강댐', '남이섬', '의암호'],
  },
  {
    id: 'city-15',
    name: '포항',
    slug: 'pohang',
    region: '경상도',
    description: '해안 산업 도시. 조용하고 저렴한 생활비.',
    image: 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22',
    rating: 4.1,
    reviewCount: 26,
    costOfLiving: 1550000,
    internetSpeed: 250,
    temperature: { summer: 26, winter: 2 },
    tags: ['해변', '산업', '저렴', '조용함'],
    highlights: ['호미곶', '죽도시장', '포스텍'],
  },
  {
    id: 'city-16',
    name: '청주',
    slug: 'cheongju',
    region: '충청도',
    description: '충북의 중심 도시. 살기 좋은 중소도시.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.2,
    reviewCount: 29,
    costOfLiving: 1600000,
    internetSpeed: 255,
    temperature: { summer: 27, winter: -1 },
    tags: ['조용함', '저렴', '안정적', '공항'],
    highlights: ['상당산성', '무심천', '육거리시장'],
  },
  {
    id: 'city-17',
    name: '순천',
    slug: 'suncheon',
    region: '전라도',
    description: '생태 도시. 자연과 함께 살 수 있는 곳.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.6,
    reviewCount: 41,
    costOfLiving: 1450000,
    internetSpeed: 230,
    temperature: { summer: 27, winter: 2 },
    tags: ['자연', '생태', '힐링', '저렴'],
    highlights: ['순천만습지', '순천만국가정원', '낙안읍성'],
  },
  {
    id: 'city-18',
    name: '경주',
    slug: 'gyeongju',
    region: '경상도',
    description: '천년 고도. 역사와 문화가 살아 숨쉬는 도시.',
    image: 'https://images.unsplash.com/photo-1555881903-f96ffe4537a8',
    rating: 4.5,
    reviewCount: 58,
    costOfLiving: 1500000,
    internetSpeed: 240,
    temperature: { summer: 27, winter: 1 },
    tags: ['역사', '문화', '관광', '한적함'],
    highlights: ['불국사', '첨성대', '대릉원'],
  },
  {
    id: 'city-19',
    name: '여수',
    slug: 'yeosu',
    region: '전라도',
    description: '밤바다가 아름다운 항구 도시.',
    image: 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22',
    rating: 4.6,
    reviewCount: 62,
    costOfLiving: 1650000,
    internetSpeed: 235,
    temperature: { summer: 27, winter: 3 },
    tags: ['해변', '항구', '야경', '힐링'],
    highlights: ['여수밤바다', '오동도', '해상케이블카'],
  },
  {
    id: 'city-20',
    name: '속초',
    slug: 'sokcho',
    region: '강원도',
    description: '동해안의 작은 항구 도시. 산과 바다가 만나는 곳.',
    image: 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22',
    rating: 4.4,
    reviewCount: 51,
    costOfLiving: 1700000,
    internetSpeed: 225,
    temperature: { summer: 24, winter: -2 },
    tags: ['해변', '산', '관광', '조용함'],
    highlights: ['속초해수욕장', '설악산', '아바이마을'],
  },
];
