import { Review } from '@/lib/types';

export const mockReviews: Review[] = [
  // Seoul reviews
  {
    id: 'review-1',
    cityId: 'city-1',
    userId: 'user-1',
    rating: 5,
    title: '서울은 디지털 노마드의 천국!',
    content: '빠른 인터넷, 24시간 카페, 뛰어난 대중교통. 일하기에 완벽한 도시입니다. 강남과 홍대에 코워킹 스페이스가 많아서 선택의 폭이 넓습니다.',
    tags: ['코워킹', '카페', '교통', '인프라'],
    helpful: 45,
    createdAt: '2024-03-15T10:30:00Z',
  },
  {
    id: 'review-2',
    cityId: 'city-1',
    userId: 'user-3',
    rating: 4,
    title: '생활비는 비싸지만 그만한 가치가 있어요',
    content: '월세와 물가가 비싼 편이지만, 제공되는 편의시설과 기회를 생각하면 충분히 가치가 있습니다. 네트워킹 이벤트도 많고요.',
    tags: ['비용', '네트워킹', '기회'],
    helpful: 32,
    createdAt: '2024-03-10T14:20:00Z',
  },
  // Busan reviews
  {
    id: 'review-3',
    cityId: 'city-2',
    userId: 'user-2',
    rating: 5,
    title: '해변에서 일하는 기분 최고!',
    content: '광안리 해변 근처 카페에서 노트북 켜고 일하면 힐링이 따로 없습니다. 서울보다 저렴하고 여유로운 분위기가 좋아요.',
    tags: ['해변', '힐링', '저렴', '카페'],
    helpful: 58,
    createdAt: '2024-03-12T09:15:00Z',
  },
  {
    id: 'review-4',
    cityId: 'city-2',
    userId: 'user-4',
    rating: 5,
    title: '부산 정착한 개발자입니다',
    content: '서울에서 부산으로 이주했는데 최고의 선택이었습니다. 생활비는 30% 저렴하고, 삶의 질은 훨씬 높아졌어요. 센텀시티에 IT 기업들도 많아서 네트워킹도 좋습니다.',
    tags: ['정착', '개발자', 'IT', '저렴'],
    helpful: 67,
    createdAt: '2024-03-08T16:45:00Z',
  },
  // Jeju reviews
  {
    id: 'review-5',
    cityId: 'city-3',
    userId: 'user-1',
    rating: 5,
    title: '제주 한 달 살기 완료!',
    content: '한 달 동안 제주에서 일했는데 정말 좋았습니다. 자연 속에서 일하니 창의력도 올라가는 것 같아요. 단, 차가 없으면 조금 불편할 수 있습니다.',
    tags: ['한달살기', '자연', '힐링', '렌트카'],
    helpful: 89,
    createdAt: '2024-03-01T11:00:00Z',
  },
  {
    id: 'review-6',
    cityId: 'city-3',
    userId: 'user-5',
    rating: 4,
    title: '여름 성수기는 피하세요',
    content: '제주는 정말 좋지만, 여름 성수기에는 숙소비가 2배로 뛰고 관광객이 너무 많아요. 봄이나 가을이 최고입니다.',
    tags: ['성수기', '비용', '계절', '팁'],
    helpful: 42,
    createdAt: '2024-02-28T13:30:00Z',
  },
  // Incheon reviews
  {
    id: 'review-7',
    cityId: 'city-4',
    userId: 'user-3',
    rating: 4,
    title: '공항 근처라 출장 많은 분께 추천',
    content: '인천공항이 가까워서 해외 출장이 잦은 노마드에게 완벽합니다. 송도는 계획도시라 깔끔하고 조용해요.',
    tags: ['공항', '송도', '조용함', '출장'],
    helpful: 28,
    createdAt: '2024-03-05T10:20:00Z',
  },
  // Daejeon reviews
  {
    id: 'review-8',
    cityId: 'city-5',
    userId: 'user-2',
    rating: 4,
    title: '조용히 일하기 좋은 도시',
    content: '대전은 큰 도시 치고 조용하고 차분한 분위기입니다. 생활비도 저렴하고 카페도 많아요. IT 기업이 있어서 네트워킹도 가능합니다.',
    tags: ['조용함', '저렴', 'IT', '카페'],
    helpful: 35,
    createdAt: '2024-02-25T15:10:00Z',
  },
  // Daegu reviews
  {
    id: 'review-9',
    cityId: 'city-6',
    userId: 'user-4',
    rating: 4,
    title: '따뜻하고 저렴한 도시',
    content: '대구는 날씨가 따뜻하고 생활비가 저렴해서 좋습니다. 동성로 주변에 카페가 많아서 작업하기 좋아요.',
    tags: ['따뜻함', '저렴', '카페', '생활'],
    helpful: 21,
    createdAt: '2024-02-20T12:00:00Z',
  },
  // Gwangju reviews
  {
    id: 'review-10',
    cityId: 'city-7',
    userId: 'user-5',
    rating: 5,
    title: '예술과 음식의 도시',
    content: '광주는 문화예술이 발달한 도시입니다. 양림동 카페거리가 정말 멋있고, 음식도 맛있어요. 저렴한 생활비도 큰 장점!',
    tags: ['예술', '문화', '미식', '저렴'],
    helpful: 38,
    createdAt: '2024-02-15T09:30:00Z',
  },
  // Jeonju reviews
  {
    id: 'review-11',
    cityId: 'city-11',
    userId: 'user-1',
    rating: 5,
    title: '슬로우 라이프의 정석',
    content: '전주는 느리게 살기에 완벽한 도시입니다. 한옥마을 근처 카페에서 일하면 힐링되는 기분이에요. 음식은 두말할 필요 없이 최고!',
    tags: ['슬로우라이프', '한옥', '미식', '힐링'],
    helpful: 72,
    createdAt: '2024-02-10T14:00:00Z',
  },
  // Gangneung reviews
  {
    id: 'review-12',
    cityId: 'city-13',
    userId: 'user-2',
    rating: 5,
    title: '커피 마시며 바다 보며 일하기',
    content: '안목 커피거리는 디지털 노마드의 성지입니다. 바다 보면서 커피 마시며 일하는 게 이렇게 좋을 줄이야. 최고입니다!',
    tags: ['커피', '해변', '힐링', '카페'],
    helpful: 94,
    createdAt: '2024-02-05T11:15:00Z',
  },
  // Jeju additional review
  {
    id: 'review-13',
    cityId: 'city-3',
    userId: 'user-3',
    rating: 5,
    title: '월정리 카페에서의 한 달',
    content: '월정리 해변 카페에서 한 달간 작업했습니다. 인터넷도 빠르고, 분위기도 좋고, 완벽했어요. 렌트카는 필수입니다!',
    tags: ['월정리', '카페', '해변', '렌트카'],
    helpful: 56,
    createdAt: '2024-01-30T10:00:00Z',
  },
  // Chuncheon reviews
  {
    id: 'review-14',
    cityId: 'city-14',
    userId: 'user-4',
    rating: 4,
    title: '호수가 있는 조용한 도시',
    content: '춘천은 소양호와 의암호가 있어서 경치가 좋습니다. 조용히 집중해서 일하기 좋은 환경이에요. 닭갈비도 맛있고요!',
    tags: ['호수', '자연', '조용함', '저렴'],
    helpful: 31,
    createdAt: '2024-01-25T13:45:00Z',
  },
  // Gyeongju reviews
  {
    id: 'review-15',
    cityId: 'city-18',
    userId: 'user-5',
    rating: 4,
    title: '역사 속에서 일하는 특별한 경험',
    content: '경주는 어디를 가나 역사 유적이 있어서 산책하며 영감을 얻기 좋습니다. 생활비도 저렴하고 조용해서 집중하기 좋아요.',
    tags: ['역사', '문화', '저렴', '조용함'],
    helpful: 44,
    createdAt: '2024-01-20T16:30:00Z',
  },
];
